mysql:
  secrets:
    MYSQL_ROOT_PASSWORD: "CHANGEME"
    MYSQL_USER: "CHANGEME"
    MYSQL_PASSWORD: "CHANGEME"

todoapp:
  namespace: todoapp
  image:
    repository: "mcisb/todoapp"
    tag: "CHANGEME"

  resources:
    requests:
      memory: "256Mi"
      cpu: "150m"
    limits:
      memory: "256Mi"
      cpu: "150m"

  secrets:
    SECRET_KEY: "CHANGEME"
    DB_NAME: "CHANGEME"
    DB_USER: "CHANGEME"
    DB_PASSWORD: "CHANGEME"
    DB_HOST: mysql-0.mysql.mysql.svc.cluster.local

  hpa:
    minReplicas: 2
    maxReplicas: 5
    cpu:
      avarageUtilization: 70
    memory:
      avarageUtilization: 70

  volumes:
    persistentVolume:
      capacity: "1Gi"
    persistentVolumeClaim:
      requestStorage: "1Gi"
